# Example of PCA on a Regression Problem

Dataset used is from UCI Superconductivity data

http://archive.ics.uci.edu/ml/datasets/Superconductivty+Data

In [1]:
%matplotlib inline

In [2]:
import numpy as np
import pandas as pd
from scipy.stats import zscore
from sklearn.metrics import accuracy_score, mean_squared_error

In [3]:
import os
os.getcwd()

'/Users/Apple/Desktop/machine_learning/PCA'

In [4]:
path0 = '/Users/Apple/Desktop/machine_learning/PCA/superconduct/'
supercond_tr = pd.read_csv(path0+'train.csv')
supercond_un = pd.read_csv(path0+'unique_m.csv')

In [5]:
supercond_tr.head()

number_of_elements  mean_atomic_mass  wtd_mean_atomic_mass  \
0                   4         88.944468             57.862692   
1                   5         92.729214             58.518416   
2                   4         88.944468             57.885242   
3                   4         88.944468             57.873967   
4                   4         88.944468             57.840143   

   gmean_atomic_mass  wtd_gmean_atomic_mass  entropy_atomic_mass  \
0          66.361592              36.116612             1.181795   
1          73.132787              36.396602             1.449309   
2          66.361592              36.122509             1.181795   
3          66.361592              36.119560             1.181795   
4          66.361592              36.110716             1.181795   

   wtd_entropy_atomic_mass  range_atomic_mass  wtd_range_atomic_mass  \
0                 1.062396          122.90607              31.794921   
1                 1.057755          122.90607              36.161939   
2                 0.975980          122.90607              35.741099   
3                 1.022291          122.90607              33.768010   
4                 1.129224          122.90607              27.848743   

   std_atomic_mass      ...        wtd_mean_Valence  gmean_Valence  \
0        51.968828      ...                2.257143       2.213364   
1        47.094633      ...                2.257143       1.888175   
2        51.968828      ...                2.271429       2.213364   
3        51.968828      ...                2.264286       2.213364   
4        51.968828      ...                2.242857       2.213364   

   wtd_gmean_Valence  entropy_Valence  wtd_entropy_Valence  range_Valence  \
0           2.219783         1.368922             1.066221              1   
1           2.210679         1.557113             1.047221              2   
2           2.232679         1.368922             1.029175              1   
3           2.226222         1.368922             1.048834              1   
4           2.206963         1.368922             1.096052              1   

   wtd_range_Valence  std_Valence  wtd_std_Valence  critical_temp  
0           1.085714     0.433013         0.437059           29.0  
1           1.128571     0.632456         0.468606           26.0  
2           1.114286     0.433013         0.444697           19.0  
3           1.100000     0.433013         0.440952           22.0  
4           1.057143     0.433013         0.428809           23.0  

[5 rows x 82 columns]

In [6]:
supercond_tr.shape

(21263, 82)

In [7]:
supercond_tr.describe()

number_of_elements  mean_atomic_mass  wtd_mean_atomic_mass  \
count        21263.000000      21263.000000          21263.000000   
mean             4.115224         87.557631             72.988310   
std              1.439295         29.676497             33.490406   
min              1.000000          6.941000              6.423452   
25%              3.000000         72.458076             52.143839   
50%              4.000000         84.922750             60.696571   
75%              5.000000        100.404410             86.103540   
max              9.000000        208.980400            208.980400   

       gmean_atomic_mass  wtd_gmean_atomic_mass  entropy_atomic_mass  \
count       21263.000000           21263.000000         21263.000000   
mean           71.290627              58.539916             1.165608   
std            31.030272              36.651067             0.364930   
min             5.320573               1.960849             0.000000   
25%            58.041225              35.248990             0.966676   
50%            66.361592              39.918385             1.199541   
75%            78.116681              73.113234             1.444537   
max           208.980400             208.980400             1.983797   

       wtd_entropy_atomic_mass  range_atomic_mass  wtd_range_atomic_mass  \
count             21263.000000       21263.000000           21263.000000   
mean                  1.063884         115.601251              33.225218   
std                   0.401423          54.626887              26.967752   
min                   0.000000           0.000000               0.000000   
25%                   0.775363          78.512902              16.824174   
50%                   1.146783         122.906070              26.636008   
75%                   1.359418         154.119320              38.356908   
max                   1.958203         207.972460             205.589910   

       std_atomic_mass      ...        wtd_mean_Valence  gmean_Valence  \
count     21263.000000      ...            21263.000000   21263.000000   
mean         44.391893      ...                3.153127       3.056536   
std          20.035430      ...                1.191249       1.046257   
min           0.000000      ...                1.000000       1.000000   
25%          32.890369      ...                2.116732       2.279705   
50%          45.123500      ...                2.618182       2.615321   
75%          59.322812      ...                4.026201       3.727919   
max         101.019700      ...                7.000000       7.000000   

       wtd_gmean_Valence  entropy_Valence  wtd_entropy_Valence  range_Valence  \
count       21263.000000     21263.000000         21263.000000   21263.000000   
mean            3.055885         1.295682             1.052841       2.041010   
std             1.174815         0.393155             0.380291       1.242345   
min             1.000000         0.000000             0.000000       0.000000   
25%             2.091251         1.060857             0.775678       1.000000   
50%             2.434057         1.368922             1.166532       2.000000   
75%             3.914868         1.589027             1.330801       3.000000   
max             7.000000         2.141963             1.949739       6.000000   

       wtd_range_Valence   std_Valence  wtd_std_Valence  critical_temp  
count       21263.000000  21263.000000     21263.000000   21263.000000  
mean            1.483007      0.839342         0.673987      34.421219  
std             0.978176      0.484676         0.455580      34.254362  
min             0.000000      0.000000         0.000000       0.000210  
25%             0.921454      0.451754         0.306892       5.365000  
50%             1.063077      0.800000         0.500000      20.000000  
75%             1.918400      1.200000         1.020436      63.000000  
max             6.992200      3.000000         3.000000     185.000000

In [8]:
supercond_tr_x = supercond_tr.iloc[:,:81]
supercond_tr_y = supercond_tr.critical_temp

In [17]:
supercond_tr_x.head()

number_of_elements  mean_atomic_mass  wtd_mean_atomic_mass  \
0                   4         88.944468             57.862692   
1                   5         92.729214             58.518416   
2                   4         88.944468             57.885242   
3                   4         88.944468             57.873967   
4                   4         88.944468             57.840143   

   gmean_atomic_mass  wtd_gmean_atomic_mass  entropy_atomic_mass  \
0          66.361592              36.116612             1.181795   
1          73.132787              36.396602             1.449309   
2          66.361592              36.122509             1.181795   
3          66.361592              36.119560             1.181795   
4          66.361592              36.110716             1.181795   

   wtd_entropy_atomic_mass  range_atomic_mass  wtd_range_atomic_mass  \
0                 1.062396          122.90607              31.794921   
1                 1.057755          122.90607              36.161939   
2                 0.975980          122.90607              35.741099   
3                 1.022291          122.90607              33.768010   
4                 1.129224          122.90607              27.848743   

   std_atomic_mass       ...         mean_Valence  wtd_mean_Valence  \
0        51.968828       ...                 2.25          2.257143   
1        47.094633       ...                 2.00          2.257143   
2        51.968828       ...                 2.25          2.271429   
3        51.968828       ...                 2.25          2.264286   
4        51.968828       ...                 2.25          2.242857   

   gmean_Valence  wtd_gmean_Valence  entropy_Valence  wtd_entropy_Valence  \
0       2.213364           2.219783         1.368922             1.066221   
1       1.888175           2.210679         1.557113             1.047221   
2       2.213364           2.232679         1.368922             1.029175   
3       2.213364           2.226222         1.368922             1.048834   
4       2.213364           2.206963         1.368922             1.096052   

   range_Valence  wtd_range_Valence  std_Valence  wtd_std_Valence  
0              1           1.085714     0.433013         0.437059  
1              2           1.128571     0.632456         0.468606  
2              1           1.114286     0.433013         0.444697  
3              1           1.100000     0.433013         0.440952  
4              1           1.057143     0.433013         0.428809  

[5 rows x 81 columns]

In [16]:
supercond_tr_y.head()

0    29.0
1    26.0
2    19.0
3    22.0
4    23.0
Name: critical_temp, dtype: float64

In [10]:
supercond_tr_scaled = supercond_tr_x.apply(zscore)

In [11]:
supercond_tr_scaled.head()

number_of_elements  mean_atomic_mass  wtd_mean_atomic_mass  \
0           -0.080058          0.046733             -0.451651   
1            0.614744          0.174269             -0.432071   
2           -0.080058          0.046733             -0.450978   
3           -0.080058          0.046733             -0.451314   
4           -0.080058          0.046733             -0.452324   

   gmean_atomic_mass  wtd_gmean_atomic_mass  entropy_atomic_mass  \
0          -0.158850              -0.611819             0.044358   
1           0.059368              -0.604180             0.777430   
2          -0.158850              -0.611658             0.044358   
3          -0.158850              -0.611739             0.044358   
4          -0.158850              -0.611980             0.044358   

   wtd_entropy_atomic_mass  range_atomic_mass  wtd_range_atomic_mass  \
0                -0.003707           0.133725              -0.053039   
1                -0.015267           0.133725               0.108900   
2                -0.218984           0.133725               0.093294   
3                -0.103615           0.133725               0.020128   
4                 0.162775           0.133725              -0.199372   

   std_atomic_mass       ...         mean_Valence  wtd_mean_Valence  \
0         0.378186       ...            -0.907755         -0.752156   
1         0.134901       ...            -1.147084         -0.752156   
2         0.378186       ...            -0.907755         -0.740164   
3         0.378186       ...            -0.907755         -0.746160   
4         0.378186       ...            -0.907755         -0.764149   

   gmean_Valence  wtd_gmean_Valence  entropy_Valence  wtd_entropy_Valence  \
0      -0.805912          -0.711705         0.186292             0.035183   
1      -1.116731          -0.719454         0.664971            -0.014779   
2      -0.805912          -0.700728         0.186292            -0.062235   
3      -0.805912          -0.706224         0.186292            -0.010538   
4      -0.805912          -0.722618         0.186292             0.113627   

   range_Valence  wtd_range_Valence  std_Valence  wtd_std_Valence  
0      -0.837959          -0.406166    -0.838372        -0.520070  
1      -0.033011          -0.362352    -0.426866        -0.450821  
2      -0.837959          -0.376957    -0.838372        -0.503304  
3      -0.837959          -0.391562    -0.838372        -0.511524  
4      -0.837959          -0.435376    -0.838372        -0.538178  

[5 rows x 81 columns]

In [27]:
from sklearn.decomposition import PCA
pca = PCA(n_components=15)
pca.fit_transform(supercond_tr_scaled)
supercond_tr_pca = pca.fit_transform(supercond_tr_scaled)

In [13]:
# Let us investigate the proportion 
# of variance explained and the elbow method
# pca.get_covariance()
pca.explained_variance_
# len(pca.explained_variance_)

array([31.53623973,  8.49098846,  7.71253473,  6.40556262,  4.76479223,
        3.06872281,  2.93416164,  2.51687507])

In [14]:
pca.explained_variance_ratio_

array([0.38931798, 0.10482209, 0.095212  , 0.0790773 , 0.05882183,
       0.03788369, 0.03622251, 0.03107107])

In [15]:
pca.explained_variance_ratio_.cumsum()

array([0.38931798, 0.49414007, 0.58935207, 0.66842937, 0.7272512 ,
       0.76513489, 0.8013574 , 0.83242847])

In [23]:
# Let us investigate the performance of the models

from sklearn.tree import DecisionTreeRegressor
DT = DecisionTreeRegressor(max_depth=6)
DT.fit(supercond_tr_scaled,supercond_tr_y)

DecisionTreeRegressor(criterion='mse', max_depth=6, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best')

In [24]:
rmse_without_pca = mean_squared_error(supercond_tr_y, DT.predict(supercond_tr_scaled))
rmse_without_pca

221.09844369292645

In [28]:
from sklearn.tree import DecisionTreeRegressor
DT_pca = DecisionTreeRegressor(max_depth=6)
DT_pca.fit(supercond_tr_pca,supercond_tr_y)

DecisionTreeRegressor(criterion='mse', max_depth=6, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best')

In [29]:
rmse_with_pca = mean_squared_error(supercond_tr_y, DT_pca.predict(supercond_tr_pca))
rmse_with_pca

256.8309833772047

In [ ]:
DT_pca.predict(supercond_tr_pca)

In [ ]:
DT.predict(supercond_tr_scaled)

In [ ]:
# Grid Search on PCA?, Can we merge the second file and then apply PCA